'use server';

import { prisma } from '@/lib/prisma';
import { MaterialBase, Chip, ProcesoFab, Seguridad } from '@/lib/types';

// --- Getters ---

export async function getMaterials(): Promise<MaterialBase[]> {
    const data = await prisma.materialBase.findMany({ orderBy: { createdAt: 'asc' } });
    return data.map(item => ({
        ...item,
        // Prisma Json type needs casting or validation if strictly typed in TS
        customVariables: item.customVariables as Record<string, any> || {}
    }));
}

export async function getChips(): Promise<Chip[]> {
    const data = await prisma.chip.findMany({ orderBy: { createdAt: 'asc' } });
    return data.map(item => ({
        ...item,
        customVariables: item.customVariables as Record<string, any> || {}
    })) as Chip[];
}

export async function getSecurityFeatures(): Promise<Seguridad[]> {
    const data = await prisma.seguridad.findMany({ orderBy: { createdAt: 'asc' } });
    return data.map(item => ({
        ...item,
        customVariables: item.customVariables as Record<string, any> || {}
    }));
}

export async function getProcesses(): Promise<ProcesoFab[]> {
    const data = await prisma.procesoFab.findMany({ orderBy: { createdAt: 'asc' } });
    return data.map(item => ({
        ...item,
        customVariables: item.customVariables as Record<string, any> || {}
    }));
}

// --- Updates (For Catalog UI) ---

export async function updateMaterial(id: string, data: Partial<MaterialBase>): Promise<MaterialBase> {
    const { customVariables, ...rest } = data;
    const updated = await prisma.materialBase.update({
        where: { id },
        data: {
            ...rest,
            customVariables: customVariables || undefined
        }
    });
    return { ...updated, customVariables: updated.customVariables as Record<string, any> };
}

export async function updateChip(id: string, data: Partial<Chip>): Promise<Chip> {
    const { customVariables, ...rest } = data;
    const updated = await prisma.chip.update({
        where: { id },
        data: {
            ...rest,
            customVariables: customVariables || undefined
        }
    });
    return { ...updated, customVariables: updated.customVariables as Record<string, any> } as Chip;
}

export async function updateProcess(id: string, data: Partial<ProcesoFab>): Promise<ProcesoFab> {
    const { customVariables, ...rest } = data;
    const updated = await prisma.procesoFab.update({
        where: { id },
        data: {
            ...rest,
            customVariables: customVariables || undefined
        }
    });
    return { ...updated, customVariables: updated.customVariables as Record<string, any> };
}

export async function updateSecurityFeature(id: string, data: Partial<Seguridad>): Promise<Seguridad> {
    const { customVariables, ...rest } = data;
    const updated = await prisma.seguridad.update({
        where: { id },
        data: {
            ...rest,
            customVariables: customVariables || undefined
        }
    });
    return { ...updated, customVariables: updated.customVariables as Record<string, any> };
}

// --- Creation (For Catalog UI) ---

export async function createMaterial(data: MaterialBase): Promise<MaterialBase> {
    const { id, customVariables, ...rest } = data;
    // We let Prisma/DB generate ID if not provided, or use provided one. 
    // Usually standard is to omit ID on create, but our mock had it.
    // If ID is passed and exists, it fails. If ID is empty string or undefined, let DB handle it?
    // Our schema says id string @id @default(uuid()).

    // We'll trust the ID if generated by client (crypto.randomUUID) or let prisma gen it if we omit it.
    // Ideally we omit it.

    // clean data
    const createData: any = { ...rest, customVariables: customVariables || {} };
    if (id && id.length > 5) createData.id = id;

    const created = await prisma.materialBase.create({ data: createData });
    return { ...created, customVariables: created.customVariables as Record<string, any> };
}

export async function createChip(data: Chip): Promise<Chip> {
    const { id, customVariables, ...rest } = data;
    const createData: any = { ...rest, customVariables: customVariables || {} };
    if (id && id.length > 5) createData.id = id;

    const created = await prisma.chip.create({ data: createData });
    return { ...created, customVariables: created.customVariables as Record<string, any> } as Chip;
}

export async function createProcess(data: ProcesoFab): Promise<ProcesoFab> {
    const { id, customVariables, ...rest } = data;
    const createData: any = { ...rest, customVariables: customVariables || {} };
    if (id && id.length > 5) createData.id = id;

    const created = await prisma.procesoFab.create({ data: createData });
    return { ...created, customVariables: created.customVariables as Record<string, any> };
}

export async function createSecurityFeature(data: Seguridad): Promise<Seguridad> {
    const { id, customVariables, ...rest } = data;
    const createData: any = { ...rest, customVariables: customVariables || {} };
    if (id && id.length > 5) createData.id = id;

    const created = await prisma.seguridad.create({ data: createData });
    return { ...created, customVariables: created.customVariables as Record<string, any> };
}

// --- History ---

export async function getMaterialHistory(id: string) {
    // We haven't implemented history table in Supabase yet.
    return [];
}
// ... similar for others if needed
